version: "3.8"

services:

  client:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    container_name: client
    networks:
      - monitoring
    ports:
      - "3001:3001"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nats:4222/health"]  # You can change the health endpoint based on your client
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change as needed
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini  # Mount config file
      - grafana-data:/var/lib/grafana
      
  nats:
    image: nats:latest
    command: -js -m 8222 --store_dir /data
    networks:
      - monitoring
    ports:
      - "4222:4222"
      - "8222:8222" #Expose monitoring port
    volumes:
      - ./nats-data:/data
      
  nats-exporter:
    image: natsio/prometheus-nats-exporter
    command: -varz -jsz=all -connz -subz http://nats:8222
    networks:
      - monitoring
    ports:
      - "7777:7777"

  consumer:
    build:
      context: .
      dockerfile: ./cmd/consumer/Dockerfile
    container_name: consumer
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - client
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nats:4222/health"]  # You can change the health endpoint based on your client
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  monitoring:

volumes:
  grafana-data:
  prometheus-data: