version: "3.8"

services:
  golang_app:
    build: .
    container_name: golang_app
    networks:
      - monitoring
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change as needed
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini  # Mount config file
      - grafana-data:/var/lib/grafana
      
  nats:
    image: nats:latest
    command: -js -m 8222
    networks:
      - monitoring
    ports:
      - "4222:4222"
      - "8222:8222" #Expose monitoring port
      
  nats-exporter:
    image: natsio/prometheus-nats-exporter
    command: -varz -jsz=all -connz -subz http://nats:8222
    networks:
      - monitoring
    ports:
      - "7777:7777"

networks:
  monitoring:

volumes:
  grafana-data:
  prometheus-data:
