global:
    scrape_interval: 1s

scrape_configs:
    - job_name: 'golang_app'
      static_configs:
        - targets: ['golang_app:8080']
    - job_name: 'nats'
      static_configs:
        - targets: ['nats-exporter:7777']
